language: python
cache: pip
python:
- '2.7'
install: pip install -r requirements.txt
before_script:
- psql -c 'create database test;' -U postgres
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: OrepW+2k+bdUgnmndMu/x1T8wHSOUw/EhVozkjgzD1pzin0mfQ4+0hud4j/0VHyL4eH1BF4iIAMrIz9bjs+1d+ybrjQEucK1tteOUYSWowBC1X0YZ6iSng4zGIPse65yd/mgAK7lx/mj6AzaBCC1/ek00iyRfrcqf+fcSor10qyIUwp1se/Ggpz1xFm68ZsZQxFs9g48pAIfaMMeUZnQUyqMX5XaA2N9eTly8fhFrzgaXHX7UrMcYYuLB2nzugTkkkea3eF2Qr2Sqcb1/yYpgRcwmHtO0iPmKzSCLZBXvdv3P0yqokPuDnU9shwCybcft8xO3qi7r8cbQCh7NXGjqYHm4kpzb+9DEPFsB3wcMnzWMRY9E3Gx2Gp9WwjUp4/sWt0xF3SQ9Mar6a7qXNlR0s9FSn6k15uQX7Lsz8mt1Wf6Ypv4YgQQUnhRqHeJ8Y+ZwKopBx6sPylbrCmN8xwcTj9zHAM4/BvRZieqANCWdabEaJ8ZkjOMj3Tqa7ODxtmFtXVbbi+fyvuG8UMyQtCV+v+Qgup605lxL7PtzWGOXai3dstuA4GEq7lhZpVcJvDVKsCXCy4RktA+3vJH9kTGFDYDgWe+RHHI8ESquEki65U3SOP6hQNV36oW4VDVfxaA/DfcOdzRgrYpgXEVEQD3k0+SSrT4oKOHDfTML/ju7hw=
  run: "python manage.py db upgrade"   
