"""empty message

Revision ID: 145e112c7127
Revises: 92cd42aad308
Create Date: 2016-07-07 22:20:14.094100

"""

# revision identifiers, used by Alembic.
revision = '145e112c7127'
down_revision = '92cd42aad308'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('spotify_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.create_index(op.f('ix_artist_spotify_id'), 'artist', ['spotify_id'], unique=False)
    op.create_foreign_key(None, 'genre', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'song', 'artist', ['artist_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_constraint(None, 'genre', type_='foreignkey')
    op.drop_index(op.f('ix_artist_spotify_id'), table_name='artist')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_table('artist')
    ### end Alembic commands ###
