"""empty message

Revision ID: 6d1e77ce5e64
Revises: 145e112c7127
Create Date: 2016-07-08 10:34:28.164513

"""

# revision identifiers, used by Alembic.
revision = '6d1e77ce5e64'
down_revision = '145e112c7127'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    ### end Alembic commands ###
