"""empty message

Revision ID: 92cd42aad308
Revises: 93cd0e8f7aff
Create Date: 2016-07-07 21:29:22.807643

"""

# revision identifiers, used by Alembic.
revision = '92cd42aad308'
down_revision = '93cd0e8f7aff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artist_spotify_id'), 'artist', ['spotify_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_spotify_id'), table_name='artist')
    ### end Alembic commands ###
