"""empty message

Revision ID: 93cd0e8f7aff
Revises: f63e77a788d8
Create Date: 2016-07-07 21:22:05.979367

"""

# revision identifiers, used by Alembic.
revision = '93cd0e8f7aff'
down_revision = 'f63e77a788d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('spotify_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'spotify_id')
    ### end Alembic commands ###
