"""empty message

Revision ID: d94681c9aaa7
Revises: None
Create Date: 2016-01-06 21:14:18.843050

"""

# revision identifiers, used by Alembic.
revision = 'd94681c9aaa7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.create_index(op.f('ix_song_popularity'), 'song', ['popularity'], unique=False)
    op.drop_index('ix_song_album', table_name='song')
    op.drop_index('ix_song_preview_url', table_name='song')
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=False)
    op.create_index(op.f('ix_user_profile_id'), 'user', ['profile_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_id'), table_name='user')
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.create_index('ix_song_preview_url', 'song', ['preview_url'], unique=False)
    op.create_index('ix_song_album', 'song', ['album'], unique=False)
    op.drop_index(op.f('ix_song_popularity'), table_name='song')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name=u'migrate_version_pkey')
    )
    ### end Alembic commands ###
